[package]
name = "groupe-04-partie-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.32"
tokio = { version = "1", features = ["full"] }
tokio-icmp-echo = "0.4.1"

